### ISSUE TITLE
Update on the Result

### ISSUE THREAD

**Issue by Ntweat** [Qidian213/deep_sort_yolov3#5]
Hi

I tested the video. The results are very bad. 

Its only 6 seconds after start of video. 

There are only 6 people but the track number is 17. 

Even the boxes are not on people.

Second image is from yolov3 on keras

![vlcsnap-2018-05-23-00h26m53s269](https://user-images.githubusercontent.com/1205924/40403421-d86fcd46-5e1f-11e8-9561-7454701ab173.png)
![vlcsnap-2018-05-23-00h27m27s755](https://user-images.githubusercontent.com/1205924/40403422-d87f57c0-5e1f-11e8-867a-08a2289c290e.png)

**Comment by Qidian213** [comment]
It seems that there has a overall offset between bounding boxes and person's position , when i use tiny_yolo i encountered this problem , it is because of different input image resolutions . But in yolov3_keras we dont need care about this . I had test different image resolutions , it all worked well . Did you change the code and could you send your video to me to have a test ?

**Comment by Qidian213** [comment]
or you can download a video file from https://motchallenge.net/ for test . In README.md i upload a test result video use the MOT challenge test video . The bad track result you got were because of boxes not on people. You can check the boxes's position right or not just after yolo detect between line 58 and line 60 of file demo.py .

**Comment by Qidian213** [comment]
The last , you can del line108 to line113 of file yolo.py . I add it because i found some negative coordinates , but the people's position of your image seems that it was not caused by it .

**Comment by Ntweat** [comment]
Can you give your email id?

**Comment by Qidian213** [comment]
xhx1247786632@gmail.com

**Comment by Ntweat** [comment]
sent

**Comment by Qidian213** [comment]
Access denied  ,  I need permission to download

**Comment by Qidian213** [comment]
Did you noticed the message "[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fe21f9ed080] Timecode frame rate 59/1 not supported" when use your video file ?  if you had google it you should found the problem , if you had test other video file you would got a better result . Every time when i use your video file it can only run 52 frames , but after i convert video coding of your video by Handbrake it can run well . And there no overall offset of boxes . So i thought the bad result was caused by your video's Timecode .

**Comment by Ntweat** [comment]
I sent you the original video

I used the ffmpeg transcoded video

Will send that video too

**Comment by Qidian213** [comment]
Can it be a shorter video file , it was to big to download . And it is to late i may reply tomorrow .

**Comment by Ntweat** [comment]
Sorry for taking longer to respond. I was traveling. 

I have sent you a new one. 

I encoded it using ffmpeg. Can you check that video.

**Comment by Qidian213** [comment]
https://drive.google.com/open?id=1NZZtrSZQiclCE388QknIWigcqgYP_ywm  , test
video ,for the yolov3's  performance  . It performs not well .

2018-05-25 21:41 GMT+08:00 Saurabh Hinduja <notifications@github.com>:

**Comment by Ntweat** [comment]
Did you change the code? Cause I am using demo on the video and the boxes are not lining up.

**Comment by Qidian213** [comment]
no

**Comment by Ntweat** [comment]
ok
will try it again. When I ran it the boxes are not lining up

**Comment by Ntweat** [comment]
Did you re-encode this video also?

**Comment by Qidian213** [comment]
no

**Comment by Ntweat** [comment]
I ran it again.. Still it is not aligned. 

Yolov3 on keras works perfectly fine.

**Comment by Ntweat** [comment]
Finally the boxes are aligned.  But the core is still dumped. 
Is there a way for it no to lose the person if detection stops for a few frames??

**Comment by Qidian213** [comment]
From the paper  “For each track k we count the number of frames since the last successful measurement association ak. This counter is incremented during Kalman filter prediction and reset to 0 when the track has been associated with a measurement. Tracks that exceed a predefined maximum age Amax are considered to have left the scene and are deleted from the track set. New track hypotheses are initiated for each detection that cannot be associated to an existing track. These new tracks are classified as tentative during their first three frames. During this time, we expect a successful measurement association at each time step. Tracks that are not successfully associated to a measurement within their first three frames are deleted” ，in code the Amax is 30  at line 40 of tracker.py .

**Comment by Ntweat** [comment]
Any idea why I am getting the error?

**Comment by Qidian213** [comment]
set writeVideo_flag = False line37 of file demo.py , can it works well ?

**Comment by Ntweat** [comment]
I need the output in video file. I am doing it on a remote server

**Comment by Qidian213** [comment]
I use opencv3.2.0 , you can have a try .

**Comment by Ntweat** [comment]
I figured it out. You are using MJPG and saving it as AVI.  AVI it uses XVID and MJPG is for MP4
